# Generated by Django 3.1.3 on 2020-11-06 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('heading_1', models.TextField(null=True)),
                ('heading_2', models.TextField(null=True)),
                ('content_1', models.TextField(null=True)),
                ('content_2', models.TextField(null=True)),
                ('content_3', models.TextField(null=True)),
                ('content_4', models.TextField(null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('mail', models.CharField(max_length=100, null=True)),
                ('condition', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=30, null=True)),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
