# Generated by Django 3.0.8 on 2020-07-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('heading_1', models.TextField()),
                ('heading_2', models.TextField()),
                ('content_1', models.TextField()),
                ('content_2', models.TextField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
