# Generated by Django 3.1.3 on 2020-11-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('review', models.TextField(null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
