# Generated by Django 3.0.8 on 2020-07-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='heading_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='heading_2',
            field=models.TextField(null=True),
        ),
    ]
