# Generated by Django 3.0.8 on 2020-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20200725_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('review', models.TextField(null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
