# Generated by Django 3.0.8 on 2020-11-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_testimonial'),
        ('acc', '0002_testimonial'),
    ]

    operations = [
    ]
