# Generated by Django 3.1.7 on 2021-03-08 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='body_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='body_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='body_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='body_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='title_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
