# Generated by Django 3.1.7 on 2021-03-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20210308_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(choices=[('image1', 'image_1.jgp'), ('image2', 'image_2.jgp'), ('image3', 'image_3.jgp'), ('image4', 'image_4.jgp'), ('image5', 'image_5.jgp'), ('image6', 'image_6.jgp'), ('image7', 'image_7.jgp'), ('image8', 'image_8.jgp')], default='image1', max_length=6),
        ),
    ]
