# Generated by Django 3.1.7 on 2021-03-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0007_post_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='present',
        ),
    ]
